-- ============================================================
--  Таблица «Хочу посмотреть» (watchlist)
--  Запустить один раз: Supabase -> SQL Editor -> вставить -> Run
--  Идемпотентно: можно запускать повторно.
-- ============================================================

create table if not exists public.watchlist (
  id           bigint generated by default as identity primary key,
  movie_id     text not null,
  user_id      text,
  user_name    text,
  movie_title  text not null,
  movie_year   text,
  movie_poster text,
  tag          text,
  added_at     timestamptz not null default now(),
  constraint watchlist_owner check (user_id is not null or user_name is not null)
);

-- один тайтл в списке не дублируется (отдельно для tg-id и для старых ников)
create unique index if not exists watchlist_uid_uniq
  on public.watchlist (movie_id, user_id) where user_id is not null;
create unique index if not exists watchlist_name_uniq
  on public.watchlist (movie_id, user_name) where user_id is null;

create index if not exists watchlist_user_idx on public.watchlist (user_id);

alter table public.watchlist enable row level security;

drop policy if exists "anon all watchlist" on public.watchlist;
create policy "anon all watchlist" on public.watchlist
  for all to anon using (true) with check (true);
